# Generated by Django 5.2.8 on 2025-11-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('semestre_cible', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], max_length=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(db_column='cree_par', on_delete=django.db.models.deletion.RESTRICT, to='comptes.administrateur')),
                ('enseignant', models.ForeignKey(db_column='enseignant_id', on_delete=django.db.models.deletion.RESTRICT, to='comptes.enseignant')),
                ('etudiants', models.ManyToManyField(db_table='cours_etudiants', related_name='cours_inscrits', to='comptes.etudiant')),
            ],
            options={
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='SessionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.CharField(max_length=512, unique=True)),
                ('qr_expiration', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(db_column='cours_id', on_delete=django.db.models.deletion.CASCADE, to='presence.cours')),
                ('enseignant', models.ForeignKey(db_column='enseignant_id', on_delete=django.db.models.deletion.RESTRICT, to='comptes.enseignant')),
            ],
            options={
                'db_table': 'session_cours',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage_scan', models.DateTimeField(auto_now_add=True)),
                ('qr_token_utilise', models.CharField(max_length=512)),
                ('valide', models.BooleanField(default=True)),
                ('etudiant', models.ForeignKey(db_column='etudiant_id', on_delete=django.db.models.deletion.CASCADE, to='comptes.etudiant')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='presence.sessioncours')),
            ],
            options={
                'db_table': 'presence',
                'unique_together': {('etudiant', 'session')},
            },
        ),
    ]
