# Generated by Django 5.2.8 on 2025-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncours',
            name='qr_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioncours',
            name='qr_token',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
