# Generated by Django 5.2.8 on 2025-11-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='semestre',
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='comptes.departement')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.formation'),
        ),
    ]
