# Generated by Django 5.2.8 on 2025-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_etudiant_semestre_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], default='S1', max_length=4),
        ),
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(choices=[('licence', 'Licence'), ('master', 'Master')], default='licence', max_length=10),
        ),
    ]
